name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .editorconfig
      - CHANGELOG.md
      - LICENSE
      - README.md
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11"
          cache: pip
      - name: Upgrade pip
        run: |
          python -m pip install pip --upgrade
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
