name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .editorconfig
      - CHANGELOG.md
      - LICENSE
      - README.md
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DJANGO_SETTINGS_MODULE: anion.settings.ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11"
          cache: pip
      - name: Upgrade pip
        run: |
          python -m pip install pip --upgrade
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check the project
        run: |
          python manage.py check --fail-level ERROR
      - name: Apply migrations
        run: |
          python manage.py migrate
